--1
SELECT empname,deptname,univname,gradyear
FROM employee E,department D, university U , graduate G
WHERE D.deptid = E.deptid AND  U.univid=G.univid AND G.empid = E.empid;


--2
SELECT EMPNAME,GRADYEAR
FROM EMPLOYEE E, GRADUATE G
WHERE E.EMPID IN (SELECT EMPID FROM EMPPROJECT GROUP BY EMPID HAVING COUNT(EMPID)=1) AND G.EMPID = E.EMPID;

--3
SELECT EMPNAME 
FROM EMPLOYEE 
WHERE HOMEZIPCODE IN (47906,47907);

--4 
SELECT PR.PROJNAME
FROM(
SELECT P.PROJNAME,G.UNIVID
FROM EMPPROJECT J,GRADUATE G,PROJECT P
WHERE J.EMPID= G.EMPID AND P.PROJID = J.PROJID AND J.ENDDATE IS NULL)PR
GROUP BY PR.PROJNAME,PR.UNIVID 
HAVING COUNT(PR.UNIVID)>1;


--5
SELECT P.PROJNAME, COUNT(J.EMPID)
FROM EMPPROJECT J, PROJECT P
WHERE J.PROJID = P.PROJID AND J.ENDDATE IS NULL
GROUP BY P.PROJNAME;

--6
SELECT D.DEPTNAME,COUNT(E.EMPID)
FROM DEPARTMENT D, EMPLOYEE E
WHERE D.DEPTID = E.DEPTID
GROUP BY D.DEPTNAME 
ORDER BY COUNT(E.EMPID)DESC;

--7


SELECT UNIVNAME 
FROM (
SELECT U.UNIVNAME,COUNT(DISTINCT(M.MGRID)) AS NMANAGERS
FROM UNIVERSITY U, PROJECTMANAGER M,GRADUATE G
WHERE M.MGRID = G.EMPID AND G.UNIVID = U.UNIVID
GROUP BY U.UNIVNAME)
WHERE NMANAGERS = (
SELECT MAX(NMANAGERS)
FROM(
SELECT U.UNIVNAME,COUNT(DISTINCT(M.MGRID)) AS NMANAGERS
FROM UNIVERSITY U, PROJECTMANAGER M,GRADUATE G
WHERE M.MGRID = G.EMPID AND G.UNIVID = U.UNIVID
GROUP BY U.UNIVNAME));

--8
SELECT E.EMPNAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPTID = D.DEPTID AND D.DEPTNAME = 'Development';

--9
SELECT U.UNIVNAME, UNIVCOUNT.STUDENTSUN
FROM(
SELECT G.UNIVID, COUNT(G.EMPID) AS STUDENTSUN
FROM GRADUATE G
WHERE G.GRADYEAR > 2010 
GROUP BY G.UNIVID)UNIVCOUNT,UNIVERSITY U
WHERE U.UNIVID = UNIVCOUNT.UNIVID AND UNIVCOUNT.STUDENTSUN >=3 ;


--10
SELECT E.EMPNAME
FROM EMPLOYEE E, GRADUATE G, UNIVERSITY U
WHERE E.EMPID = G.EMPID AND G.GRADYEAR > 2000 AND G.UNIVID = U.UNIVID AND U.UNIVNAME = 'Purdue';

--11
SELECT  E.EMPNAME
FROM
(SELECT E.EMPID EID,J.PROJID EPROJ,E.HOMEZIPCODE EZIP
FROM EMPLOYEE E, EMPPROJECT J
WHERE E.EMPID = J.EMPID AND J.ENDDATE IS NULL)WORKERS,
(SELECT M.MGRID MID, M.PROJID MPROJ, E.HOMEZIPCODE MZIP
FROM PROJECTMANAGER M, EMPLOYEE E
WHERE M.ENDDATE IS NULL AND M.MGRID = E.EMPID)MANAGERS,
EMPLOYEE E
WHERE WORKERS.EID != MANAGERS.MID AND WORKERS.EPROJ = MANAGERS.MPROJ AND WORKERS.EZIP = MANAGERS.MZIP AND E.EMPID = WORKERS.EID ;


--12

SELECT P.PROJNAME 
FROM(
SELECT J.PROJID, COUNT(J.EMPID)AS NEMP
FROM EMPPROJECT J
WHERE J.ENDDATE IS NULL
GROUP BY J.PROJID)C,PROJECT P 
WHERE C.NEMP>=2 AND C.PROJID = P.PROJID;

--13 


SELECT E.empname,D.avgdays,P.nprojects 
FROM employee E,(SELECT AVG(TO_DATE(NVL(EndDate,CURRENT_DATE))-TO_DATE(StartDate)+1) AS avgdays,empid from empproject GROUP BY empid)D,
(SELECT empid,count(distinct(projid))as nprojects FROM empproject GROUP BY empid)P
WHERE E.empid=D.empid AND E.empid=P.empid;



/*14*/

SELECT P.projname,E.empname FROM(SELECT MAX(ndays) AS max,projid FROM (SELECT (TO_DATE(NVL(EndDate,CURRENT_DATE))-TO_DATE(StartDate)+1)AS ndays,mgrid,projid from projectmanager) GROUP BY projid
)A,(SELECT (TO_DATE(NVL(EndDate,CURRENT_DATE))-TO_DATE(StartDate)+1)AS ndays,mgrid,projid from projectmanager)B, project P,employee E WHERE A.projid = B.projid AND A.max = B.ndays AND B.projid = P.projid AND E.empid = B.mgrid;


/*15*/
SELECT E.EMPNAME
FROM EMPLOYEE E 
WHERE E.EMPID IN
(SELECT J.EMPID
FROM EMPPROJECT J, PROJECTMANAGER M
WHERE J.EMPID = M.MGRID AND J.PROJID = M.PROJID AND M.ENDDATE IS NULL AND J.STARTDATE != M.STARTDATE);
